import { Rubik } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"


const rubik = Rubik({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	display: 'swap',
})

import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Bookmarks App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' >
			<body className={`${rubik.className} bg-white dark:bg-slate-900 antialiased`}>
			<ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
				{children}</ThemeProvider></body>
		</html>
	)
}
